export type Factor = {
  cls: string; label: string; share: number; surveyed: number;
  irc_low: number; irc_point: number | null; irc_high: number; composite: boolean;
};
export type Junction = {
  code: string; arms: string[]; daily_veh: number; peak_start: string;
  lat: number; lon: number; jda_name: string;
  signal_cluster: string; location_confidence: string;
  peak_veh: number; peak15: number; phf: number; through_pct: number;
  corridor_through_pct: number; pcu_surveyed: number; pcu_corrected: number;
  pcu_band: [number, number]; uplift_pct: number;
  matrix_veh: number[][]; matrix_pcu: number[][];
  composition: { cls: string; label: string; count: number; share: number }[];
  profile: { t: string; v: number }[];
};
export type Corridor = {
  meta: { corridor: string; road: string; jda_scheme: string; city: string; survey_dates: string[];
          analysis_date: string; n_junctions: number; bins_parsed: number; note: string };
  audit: {
    arithmetic: { discrepancies: number; understate: number; overstate: number; net_grand_total: number };
    derived_sheets: { cells_checked: number; exact: number; conclusion: string };
    day2: { series: number; identical: number; greater: number; smaller: number };
    pcu: { factors: Factor[]; uplift_floor_pct: number; band_low_pct: number; band_high_pct: number };
    flow_diagram: { ref_errors: number; files_affected: number; mislabelled: [string, number, string][] };
    survey_design: string[];
  };
  constraints: {
    corridor_km: number; stations: number; pier_radius_m: number;
    hard_free: number; hard_free_pct: number; longest_clear_runs_m: number[];
    totals: Record<string, number>; median_openings: number;
    uturn_possible: number; uturn_per_km: number;
    opening_classes: Record<string, number>;
  } | null;
  capacity: {
    observed_vs_planning_ratio: number; lane_model_applicable?: boolean; horizon_year: number;
    approaches_ok_after_grade_separation: number;
    widths: Record<string, { width_m: number; lanes_per_dir: number; capacity_pcu_hr: number }>;
    relief: { junction: string; approach: string; through_pct: number; peak_pcu: number;
              residual_pcu: number; vc_before: number; vc_after: number; los_after: string }[];
    growth: { growth_pct: number; multiple: number; binding_need_pcu: number }[];
    assumptions: { base_year: number; design_horizon_years: number;
                   base_capacity_pcu_per_dir: number; base_width_per_dir_m: number;
                   capacity_source: string };
    design_life?: { junction: string; approach: string; vc_after: number;
                    fails_low: number; fails_med: number; fails_high: number }[];
    design_life_first_failure_med?: number;
    design_life_last_failure_med?: number;
    design_life_survives_horizon?: number;
  } | null;
  delay: {
    corridor_km: number; free_flow_min: number; peak_delay_min: number;
    peak_journey_min: number; effective_kmh: number; worst_direction: string;
    direction_delay_min: Record<string, number>;
    assumptions?: { free_flow_kmh?: number; [k: string]: unknown };
    spillback_count: number; oversaturated_count: number; n_approaches: number;
    through_journey_min_after: number; saving_min_per_trip: number;
    approaches: { junction: string; approach: string; vc: number; queue_vehicles: number;
                  queue_m: number; storage_m: number | null; upstream: string | null;
                  spillback: boolean; minutes_to_spillback: number | null;
                  mean_delay_min: number }[];
  } | null;
  economics: {
    annual_cost_crore: number[]; annual_cost_after_crore: number[];
    annual_benefit_crore: number[]; benefit_to_first_failure_crore: number[] | null;
    pcu_per_vehicle: number;
    years_to_first_failure: number | null; mean_hours_over: number;
    delay_veh_hr_day: number; total_excess_pcu_day: number;
    assumptions: { vot_status: string; working_days: number[]; excluded: string[] };
    approaches: { junction: string; approach: string; hours_over: number;
                  excess_pcu: number }[];
  } | null;
  standards: {
    jda_turning_claim_pct: number; measured_turning_pct: number; claim_overstatement: number;
    jmrc_dpr_pcu: Record<string, number>; survey_pcu: Record<string, number>;
    interchange_warrant_pcu: number;
    interchange: { junction: string; corridor_arms_pcu: number; floor_vs_warrant: number }[];
    zebra_ceiling_pcu_dir: number; zebra_over: number; zebra_total: number;
    median: { openings: number; gaps: number; closer_than_500m: number; closest_m: number;
              median_gap_m: number; within_18_20m: number; widths_checked: number };
    surveys_required_by_sp90: number; surveys_run: number;
    pedestrian_row_in_sp41_table_3_1: boolean; pedestrian_row_filled: boolean;
    unverified: string[];
  } | null;
  safety: {
    base_counts: Record<string, number>; base_total: number;
    junctions: { junction: string; jda_name: string; today_points: number;
                 scheme_junction_points: number; today_crossing_exposure: number;
                 scheme_crossing_exposure: number; uturn_crossing_exposure: number;
                 change_pct: number | null }[];
    junctions_worse: number; mean_change_pct: number; pedestrian_column_present: boolean;
  } | null;
  profiles: {
    los_distribution: Record<string, number>; approach_hours_total: number;
    approach_hours_F: number; f_share_pct: number; mean_hours_over: number;
    series_available: string[];
  } | null;
  exhibits: {
    tornado: { base_pcu: number; net_low_pct: number; net_high_pct: number;
               classes: { veh_class: string; share_pct: number; surveyed_factor: number;
                          irc_low: number | null; irc_high: number | null; exact: boolean;
                          swing_low_pct: number; swing_high_pct: number; magnitude: number }[] };
    corridor_order: string[];
    omitted: Record<string, string>;
    series_available: string[];
  } | null;
  scheme: {
    indo_hcm_no_uturn_chapter: string;
    csir_crri_design_gap_s: number;
    csir_crri_design_source: string;
    follow_up_measured_s: number[];
    uturn_detour?: { junction: string; bay: string; demand: number;
      bay_beyond_drawing: boolean; junction_chainage_m?: number; bay_chainage_m?: number;
      one_way_m?: number | null; detour_m?: number | null;
      veh_km_per_hour?: number | null }[];
    detour_min_m?: number; detour_max_m?: number; detour_mean_m?: number;
    detour_mean_typical_m?: number; detour_veh_km_per_hour?: number;
    detour_veh_km_typical?: number; detour_bays_measured?: number;
    detour_bays_beyond_drawing?: number; detour_outliers_excluded?: number;
    gap_evidence_spread: { label: string; t_c: number; t_f: number; unservable: number;
      no_viable_gap: number; of: number; source: string; geometric_match: string }[];
    gap_conclusion_holds_in: number;
    gap_bases_tested: number;
    uturn_analogue: string;
    gap_direction_note: string;
    two_wheeler_gap_basis: string;
    gap_benchmark?: { junction: string; approach: string; t_c_optimistic: number;
                      t_c_conservative: number; t_c_required: number; margin_s: number;
                      works_at_our_optimistic: boolean }[];
    gap_required_median_s?: number; gap_ours_median_s?: number; gap_margin_s?: number;
    irc_sp41_car_gap_s?: number; gap_source?: string;
    no_gap_vc_threshold: number; fails_conservative: number; fails_optimistic: number;
    no_viable_gap: number; forced_uturns_per_hour: number;
    s1_serviceable: number; n_junctions: number;
    uturns: { junction: string; approach: string; uturn_demand: number;
              conflicting_flow: number; cap_conservative: number;
              vc_conservative: number }[];
    scenarios: { junction: string; jda_name: string; s0_vc: number;
                 s1_uturn_vc_cons: number; s1_works: boolean;
                 s2_vc: number; s2_los: string }[];
  } | null;
  sensitivity: {
    queue?: { packing: number; footprint: number; lane_cap: number;
              spillback: number; total: number }[];
    queue_spillback_min?: number | null; queue_spillback_max?: number | null;
    queue_spillback_central?: number | null;
    combinations_uturn?: number; combinations_elevated?: number;
    combinations_queue?: number;
    queue_robust?: boolean | null;
    combinations: number; uturn_robust: boolean;
    uturn: Record<string, { fails: number; of: number }>;
    elevated_all_pass_combinations: number; elevated_total_combinations: number;
    most_influential: string | null; swing: number; assumption_driven: boolean;
  } | null;
  junctions: Junction[];
  corridor: {
    through_pct_mean: number; through_pct_range: [number, number];
    order_best: string[]; order_margin_pct: number; order_conclusive: boolean;
    order_candidates: { cost: number; order: string[] }[];
    links: Record<string, string | number>[];
  };
};
